version: "3"

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    #command for v1.2.0 as outline stopped using yarn
    command: node build/server/index.js
    #env_file: ./stack.env
    restart: always
    #ports:
    #  - "3000:3000"
    volumes:
      - /volume1/Docker/Outline/data:/var/lib/outline/data
    depends_on:
      - outline-redis
    networks:
      outline-network:
        ipv4_address: 192.168.53.10

  outline-redis:
    image: redis
    container_name: outline-redis
    #env_file: ./stack.env
    restart: always
    expose:
      - "6379"
    volumes:
      - /volume1/Docker/Outline/redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      outline-network:
        ipv4_address: 192.168.53.12

  outline-web:
    image: nginx
    container_name: outline-web
    ports:
    #  - '580:80'
      - '5443:5443'
    links:
      - outline
    restart: always
    volumes:
      - /volume1/Docker/Outline/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - /volume1/Docker/Outline/cert/tls.crt:/etc/nginx/ssl/tls.crt:ro
      - /volume1/Docker/Outline/cert/tls.key:/etc/nginx/ssl/tls.key:ro
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    #environment:
      # NGINX_HOST: mvserver01.home.truxtons.com:5443
      # NGINX_PORT: 80
      # NGINX_PORT_SSL: 443
    networks:
      outline-network:
        ipv4_address: 192.168.53.13
