networks:
  outline-network:
    external: true
    name: outline_outline-network

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: ${OUTLINE_CONTAINER_NAME}
    user: ${OUTLINE_WEB_USER_GROUP}
    #command for v1.2.0 as outline stopped using yarn
    command: node build/server/index.js
    #env_file: ./stack.env
    environment:
      NODE_ENV: ${NODE_ENV}
      URL: ${URL}
      TRUST_PROXY: ${TRUST_PROXY}
      PORT: ${PORT}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE}
      PGSSLMODE: ${PGSSLMODE}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_CONNECTION_POOL_MIN: ${DATABASE_CONNECTION_POOL_MIN}
      DATABASE_CONNECTION_POOL_MAX: ${DATABASE_CONNECTION_POOL_MAX}
      REDIS_URL: ${REDIS_URL}
      FILE_STORAGE: ${FILE_STORAGE}
      FILE_STORAGE_LOCAL_ROOT_DIR: ${FILE_STORAGE_LOCAL_ROOT_DIR}
      FILE_STORAGE_UPLOAD_MAX_SIZE: ${FILE_STORAGE_UPLOAD_MAX_SIZE}
      ALLOWED_DOMAINS: ${ALLOWED_DOMAINS}
      EMAIL_ENABLED: ${EMAIL_ENABLED}
      SMTP_SERVICE: ${SMTP_SERVICE}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      RATE_LIMITER_ENABLED: ${RATE_LIMITER_ENABLED}
      RATE_LIMITER_REQUESTS: ${RATE_LIMITER_REQUESTS}
      RATE_LIMITER_DURATION_WINDOW: ${RATE_LIMITER_DURATION_WINDOW}
      ENABLE_UPDATES: ${ENABLE_UPDATES}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ${OUTLINE_LOCAL_DATA_DIR}:/var/lib/outline/data
      - ${OUTLINE_LOCAL_FAVICON_16}:/opt/outline/public/images/favicon-16.png
      - ${OUTLINE_LOCAL_FAVICON_32}:/opt/outline/public/images/favicon-32.png
      - ${OUTLINE_LOCAL_ICON_192}:/opt/outline/public/images/icon-maskable-192.png
      - ${OUTLINE_LOCAL_ICON_512}:/opt/outline/public/images/icon-maskable-512.png
      - ${OUTLINE_LOCAL_ICON_1024}:/opt/outline/public/images/icon-maskable-1024.png
    depends_on:
      - outline-redis
    networks:
      outline-network:
        ipv4_address: 192.168.53.10

  outline-redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME}
    #env_file: ./stack.env
    restart: always
    expose:
      - "6379"
    volumes:
      - ${REDIS_CONFIG}:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      outline-network:
        ipv4_address: 192.168.53.12

  outline-web:
    image: nginx
    container_name: ${WEB_CONTAINER_NAME}
    ports:
    #  - '580:80'
      - '5443:5443'
    links:
      - outline
    restart: always
    volumes:
      - ${WEB_NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - ${WEB_CERT}:/etc/nginx/ssl/tls.crt:ro
      - ${WEB_CERT_KEY}:/etc/nginx/ssl/tls.key:ro
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      outline-network:
        ipv4_address: 192.168.53.13
